services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chat2db_backend
    volumes:
      - ./data:/data
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - OLLAMA_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=llama2
      - CURL_CA_BUNDLE=
      - REQUESTS_CA_BUNDLE=
      - HF_HUB_OFFLINE=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - chat2db_net
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    container_name: chat2db_frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - chat2db_net
    restart: unless-stopped

networks:
  chat2db_net:
    driver: bridge